name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Configure cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: ${{ runner.os }}-gradle-nix-${{ hashFiles('**/*.gradle*', '**/*.nix', '**/*.lock') }}
          restore-prefixes-first-match: |
            ${{ runner.os }}-gradle-nix-
          paths: |
            .gradle/caches
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Build the devenv shell
        run: devenv test
      - name: Build with Gradle
        run: devenv tasks run gradle:build
